version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '2306:2306'
    command: --default-authentication-plugin=caching_sha2_password

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails tailwindcss:build && bundle exec rails s -p 2000 -b '0.0.0.0'"
    volumes:
      - .:/test-app
    ports:
      - 2000:2000
    stdin_open: true
    tty: true
    depends_on:
      - db
volumes:
  mysql_volume: